export const ActionTypes = {
    GET_ALL_COUNTRIES: "GET_ALL_COUNTRIES",
    GET_COUNTRY_DETAIL: "GET_COUNTRY_DETAIL",
    GET_COUNTRIES_BY_ID: "GET_COUNTRIES_BY_ID",
    GET_COUNTRIES_BY_NAME: "GET_COUNTRIES_BY_NAME",
    GET_ACTIVITIES: "GET_ACTIVITIES",
    GET_ACTIVITIES_WITH_COUNTRIES: "GET_ACTIVITIES_WITH_COUNTRIES",
    SET_FILTERED_COUNTRIES: 'SET_FILTERED_COUNTRIES',
    SET_SORT_OPTION: 'SET_SORT_OPTION',
    POST_ACTIVITIES: "POST_ACTIVITIES",
    DISASSEMBLE_DETAIL: "DISASSEMBLE_DETAIL",
    DISASSEMBLE_COUNTRIES: "DISASSEMBLE_COUNTRIES",
    NEXT_PAGE: "NEXT_PAGE",
    PREV_PAGE: "PREV_PAGE"
};
